### ISSUE TITLE
Tag image releases

### ISSUE THREAD

**Issue by abursavich** [GoogleCloudPlatform/gcr-cleaner#52]
It would be very helpful if images were tagged with their version. Currently, `latest` is the only tag.

<img width="626" alt="Screen Shot 2021-11-01 at 11 44 06 AM" src="https://user-images.githubusercontent.com/1512418/139724751-a8520933-0011-473d-bbfd-5a8e4ef5ab9d.png">

**Comment by sethvargo** [comment]
I don't have a great way to automate this today, but I agree it would be good to do.

**Comment by anouarchattouna** [comment]
Hi @sethvargo, we are deploying the whole stack using [gcr-cleaner terraform module](https://registry.terraform.io/modules/mirakl/gcr-cleaner/google/latest) that takes the docker image in input `gcr_cleaner_image` which defaults to `gcr.io/gcr-cleaner/gcr-cleaner:latest`.
Without specifying an image tag, and from `terraform` perspective, the Cloud Run Service will never be updated when running `terraform apply` because it considers that image doesn't change!

We will appreciate the effort if you could find out a way to add tags to those images.
